In [1]:
import numpy as np
import pandas as pd
from pandas import DataFrame

s_a = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
s_a2 = pd.Series([0.1, 0.2, 0.3, 0.4], index=['a', 'b', 'c', 'd'])
s_a3 = pd.Series([0.1, 0.2, 0.3, 0.4], index=['d', 'c', 'b', 'a'])

## 1. Series basics

a. print the values of s_a

b. print the index of s_a

c. print the data type of s_a

d. print the shape of s_a

e. print the number of dimensions of s_a

f. print the size of s_a

g. print the memory usage of s_a

h. create a Series s_b with the same values as s_a but with an index of [1,2,3,4].

i. create a Series s_c with the same values as s_b, but with a data type of int8 instead of int64. Check the difference in memory usage between s_b and s_c.


In [8]:
print(s_a.values)
print(s_a.index)
print(s_a.shape)
print(s_a.size)
print(s_a.memory_usage())
s_b = pd.Series(s_a.values, index=[1, 2, 3, 4])
print("s_b= ", s_b)
s_c = pd.Series(s_b.values, dtype='int8')
print("s_c = ", s_c)
print("s_b memory usage = ", s_b.memory_usage(), " s_c memory usage = ", s_c.memory_usage())

[1 2 3 4]
Index(['a', 'b', 'c', 'd'], dtype='object')
(4,)
4
236
s_b=  1    1
2    2
3    3
4    4
dtype: int64
s_c =  0    1
1    2
2    3
3    4
dtype: int8
s_b memory usage =  64  s_c memory usage =  136


## 2. Creating Series

a. create a Series s_b with the same values as s_a but with an index of [1,2,3,4].

b. create a Series s_c with the same values as s_b, but with a data type of int8 instead of int64. Check the difference in memory usage between s_b and s_c.

c. create a Series s_d with the same values as s_b, but use np.arange() to define the index. The range should start at 1 and end at the number of elements in s_d.

d. create a Series s_e with the same values, but use a dictionary to define the Series.

e. create a Series s_f with the index the numbers written out as strings (e.g. 'one', 'two', 'three', 'four').

In [46]:
# a
s_b = pd.Series(s_a.values, index=[1, 2, 3, 4])
print(s_b)
# b
s_c = pd.Series(s_b.values, index=pd.Index([1, 2, 3, 4],dtype='int8'), dtype='int8') # gotta specify the index type too to make it all 'int8' dtype
print(f'Memory usage s_b: {s_b.memory_usage()} - Memory usage s_c: {s_c.memory_usage()}')
#c
s_d = pd.Series(s_b.values, index=np.arange(len(s_b.values)))
print("s_b = ")
print(s_b)
#d
s_e = pd.Series({1:1, 2:2, 3:3, 4:4})
print("s_e = \n", s_e)
#e
s_f = pd.Series(s_e.values, index=['one', 'two', 'three', 'four'])
print("s_Fe = \n", s_f)

1    1
2    2
3    3
4    4
dtype: int64
Memory usage s_b: 64 - Memory usage s_c: 8
s_b = 
1    1
2    2
3    3
4    4
dtype: int64
s_e = 
 1    1
2    2
3    3
4    4
dtype: int64
s_Fe = 
 one      1
two      2
three    3
four     4
dtype: int64


### 3. Dataframes basics and creation

a. create a DataFrame df_a with the values of s_a and s_b as columns.

b. create a DataFrame df_b with the values of s_a2 and s_a3 as columns. Did you expact this result? Can you explain why the values are not aligned? _Tip: check the index of the Series._

c. create a Dataframe df_c based on a two-dimensional numpy array created with np.arange().

d. create a Dataframe df_d like df_c. The index should be ['a', 'b', 'c'] and the columns should be ['x', 'y', 'z', 'w'].

e.  Try to change te first indexvalue of df_c. What happens? Can you explain why this happens?

In [39]:
df_a = pd.DataFrame({'s_a':s_a, 's_b':s_a2})
print(df_a)
print()

df_b = pd.DataFrame({'s_a2': s_a2, 's_a3': s_a3})
print(df_b)
print()

df_c = pd.DataFrame(np.arange(4).reshape(2, 2))
print(df_c)
print()

df_d = pd.DataFrame(np.arange(12).reshape(3, 4), index=['a', 'b', 'c'], columns=['x', 'y', 'z', 'w'])
print(df_d)
print()

df_c.index[0] = 'd' # error cause it's trying to change the index but indexer are immutable

   s_a  s_b
a    1  0.1
b    2  0.2
c    3  0.3
d    4  0.4

   s_a2  s_a3
a   0.1   0.4
b   0.2   0.3
c   0.3   0.2
d   0.4   0.1

   0  1
0  0  1
1  2  3

   x  y   z   w
a  0  1   2   3
b  4  5   6   7
c  8  9  10  11



TypeError: Index does not support mutable operations