# 1. Understanding how integers and other datatypes are stored in Python
a. Create an integer with value 1.
b. Check how many bytes the variable occupies in memory (use getsizeof() of the sys module)
c. Can you explain the difference with an integer in C which occupies 2 or 4 bytes in memory?

In [7]:
from sys import getsizeof

from flatbuffers.packer import float32

b =  100000
print(getsizeof(b))

28


# 2. Understanding the difference between lists and np arrays
a. Create a Python list with 3 one-digit integers. 
b. Append one item to the list with string value "X".
c. Check how many bytes the list occupies in memory. 
_In case of a list, the total size is the sum of the list-object + the size of each seperate object in the list (as the list object only contain references to the list objects). You can use a __[list-comprehension](https://www.w3schools.com/python/python_lists_comprehension.asp)__ to loop through all the items_
d. Now create a Numpy ndarray with the same 3 integers. Check the objectsize with getsizeof(). How many bytes does the ndarray occupy
e. Also check the size of an indivdual element in the array with the 'itemsize' property of the ndarray object. How many bytes does one integer occupy? Explain the difference with a list object. _Using the list-comprehension as done with the list object will give confusing results as Python will convert the stored integer to a fully fledged "int" python object and will show the 28 byes of that object).
f. Now 'append' an extra item with value 4 to the ndarray. Check the size of the ndarray again. How many bytes where added? Why?

In [8]:
my_list = [1, 2, 3]
my_list.append("X")

import sys

# Size of the list object itself
list_size = sys.getsizeof(my_list)

# Size of each individual object in the list
individual_sizes = sum(sys.getsizeof(item) for item in my_list)

# Total size
total_list_size = list_size + individual_sizes

print(f"Size of the list object: {list_size} bytes")
print(f"Size of individual elements: {individual_sizes} bytes")
print(f"Total size of the list: {total_list_size} bytes")

import numpy as np

my_array = np.array([1, 2, 3])
array_size = sys.getsizeof(my_array)

print(f"Size of the ndarray: {array_size} bytes")
element_size = my_array.itemsize
print(f"Size of one integer in the ndarray: {element_size} bytes")
my_array = np.append(my_array, 4)
new_array_size = sys.getsizeof(my_array)

print(f"Size of the new ndarray: {new_array_size} bytes")
size_increase = new_array_size - array_size
print(f"Bytes added: {size_increase} bytes")


Size of the list object: 88 bytes
Size of individual elements: 126 bytes
Total size of the list: 214 bytes
Size of the ndarray: 136 bytes
Size of one integer in the ndarray: 8 bytes
Size of the new ndarray: 144 bytes
Bytes added: 8 bytes


my_list.append("X")
# 3. Creating Numpy arrays
a. Array a1 has 10 ones of type float
b. Array a2 has a range of numbers from 50 to (and including) 100 with steps of 2
c. Array a3 has 10 random integers between 0 and 100. To do so, first create a random number generator with the default seed, then use the 'integers' method to create the array. _The seed makes sure that the random numbers are the same each time the code is executed._
d. Array a4 has to contain the values of list 'l_ex3' 
e. Array a5 is a compact copy a2. Look for a dtype with a smaller size knowing that the values will never be higher then 100. _As you will be working with big datasets, reducing the size of the arrays will have a big impact on processing the data._
f. Array a6 is an array of ones with 2 dimensions of 2 by 4.  


In [2]:
import numpy as np
a1 = np.ones(10, dtype=float)
print(a1)
print("a1 = ", a1)

a2 = np.arange(50, 101, 2)
print(a2)
print("a2 = ", a2)

random = np.random.default_rng(303)
a3 = random.integers(0, 101, 10)
print("a3 = ", a3)

l_oef3= [1,2,3.14,4]
a4 = np.array(l_oef3, dtype=np.float16)
print("a4 = ", a4)

a5 = np.array(a2, dtype=np.int8)
print("a5 = ", a5)

a6 = np.ones((2, 4))
print(a6)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
a1 =  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80  82  84
  86  88  90  92  94  96  98 100]
a2 =  [ 50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80  82  84
  86  88  90  92  94  96  98 100]
a3 =  [41 21 88 42 48 81 27 27 78 82]
a4 =  [1.   2.   3.14 4.  ]
a5 =  [ 50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80  82  84
  86  88  90  92  94  96  98 100]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
