In [6]:
import numpy as np
import sklearn.datasets as ds
import numpy as np
wine_x= np.array(ds.load_wine().data)
wine_y= np.array(ds.load_wine().target)
descr= ds.load_wine().DESCR
print(descr)

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

:Number of Instances: 178
:Number of Attributes: 13 numeric, predictive attributes and the class
:Attribute Information:
    - Alcohol
    - Malic acid
    - Ash
    - Alcalinity of ash
    - Magnesium
    - Total phenols
    - Flavanoids
    - Nonflavanoid phenols
    - Proanthocyanins
    - Color intensity
    - Hue
    - OD280/OD315 of diluted wines
    - Proline
    - class:
        - class_0
        - class_1
        - class_2

:Summary Statistics:

============================= ==== ===== ======= =====
                                Min   Max   Mean     SD
============================= ==== ===== ======= =====
Alcohol:                      11.0  14.8    13.0   0.8
Malic Acid:                   0.74  5.80    2.34  1.12
Ash:                          1.36  3.23    2.36  0.27
Alcalinity of Ash:            10.6  30.0    19.5   3.3
Magnesium:                    70.0 162.0    99.7  14.3

## 1. Fancy Indexing
a. Select the 1st, 5th and 10th row of wine_x. Do it with one statement.
b. Pick a sample of 5 rows of wine_x. Use the random module of numpy.
c. Pick a sample of 20 rows of wine_x. Show only columns 1 to 3. Use combined indexing.
d. In column 0 of wine_x change the values of row 5,20,38,45,60 to 0.

In [7]:
wine_x[[0,4,9]]
rng = np.random.default_rng(seed=42)
wine_x[rng.choice(range(0, len(wine_x)), 5, replace=False)]
wine_x[rng.choice(range(0, len(wine_x)), 5, replace=False), 0:3]
wine_x[[5,20,38,45,60],0]=0
print(wine_x)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]
