In [1]:
import numpy as np
import sklearn.datasets as ds

a = np.array(ds.load_iris().data)
b= a[:,1]

# 1. Numpy Array Attributes
 a. Get the number of dimensions of array a. Use the correct attribute
 b. Get the shape of the array. How many rows and columns does the array have.
 c. What datatype is used in the array?

In [5]:
print(a.ndim)
print(a.shape) # has 150 rows and 4 columns (4 elements each row)
print(a.size)
print(a.dtype)

2
(150, 4)
600
float64


# 2. Indexing
a. From array b, get the 3th value (should be 3.2)
b. From array b, get the 3th last value  (should be 3.0)
c. From array a, get the value of the 3th column of the 91st row of array a (should be 4.4)
d. From array a, from the last row get the first column (should be 5.9)

In [10]:
print(b[2])
print(b[-3])
print(a[90, 2])
print(a[-1, 0])

3.2
3.0
4.4
5.9


## 3. Slicing
a. From array b, get the first 10 elements
b. From array b, get elements starting from the 10th element until the 20th element (including the 20th elemement)
b. From array b, get all the elements after the 50th element
d. From array b, display the last 5 elements
e. From array b, display only every 3th element
f. From array b, display each 5th element from the first 100 elements
g. From array a, display the rows of the first 10 elements
h. From array a, display the last two columns of the rows with index 10 to 20 (20 not included)
i. From array a, display the second column of each second element.
j. Based on array a, make a new array c with the 20 first rows with column 1 and 2. Make sure changes in the new array are not applied on the original aray.
k. change element c[0,0] to 1. Check if a[0,0] is not changed
l. Based on array a, make a new array l with 100 by 6 instead of 150 by 4.
The outputs should look like this:
```
a=[3.5 3.  3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1]
b=[3.1 3.7 3.4 3.  3.  4.  4.4 3.9 3.5 3.8 3.8]
c=[3.2 3.2 3.1 2.3 2.8 2.8 3.3 2.4 2.9 2.7 2.  3.  2.2 2.9 2.9 3.1 3.  2.7
 2.2 2.5 3.2 2.8 2.5 2.8 2.9 3.  2.8 3.  2.9 2.6 2.4 2.4 2.7 2.7 3.  3.4
 3.1 2.3 3.  2.5 2.6 3.  2.6 2.3 2.7 3.  2.9 2.9 2.5 2.8 3.3 2.7 3.  2.9
 3.  3.  2.5 2.9 2.5 3.6 3.2 2.7 3.  2.5 2.8 3.2 3.  3.8 2.6 2.2 3.2 2.8
 2.8 2.7 3.3 3.2 2.8 3.  2.8 3.  2.8 3.8 2.8 2.8 2.6 3.  3.4 3.1 3.  3.1
 3.1 3.1 2.7 3.2 3.3 3.  2.5 3.  3.4 3. ]
d=[3.  2.5 3.  3.4 3. ]
e=[3.5 3.1 3.4 3.1 3.  4.4 3.8 3.7 3.4 3.5 3.1 4.2 3.5 3.4 3.2 3.  3.7 3.2
 2.8 2.4 2.  2.9 3.  2.5 2.5 3.  2.9 2.4 3.  2.3 2.6 2.3 2.9 2.8 3.  3.
 2.5 2.7 2.8 3.8 3.2 2.7 2.8 3.  2.8 3.  3.  3.1 3.3 3. ]
f=[3.6 3.1 4.  3.8 3.4 3.2 3.1 3.4 3.8 3.3 2.8 2.7 2.9 2.5 2.9 2.6 3.  2.5
 2.7 2.8]
g1=[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
g2=[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
h=[[1.5 0.2]
 [1.6 0.2]
 [1.4 0.1]
 [1.1 0.1]
 [1.2 0.2]
 [1.5 0.4]
 [1.3 0.4]
 [1.4 0.3]
 [1.7 0.3]
 [1.5 0.3]]
i=[3.5 3.2 3.6 3.4 2.9 3.7 3.  4.  3.9 3.8 3.4 3.6 3.4 3.4 3.4 3.1 4.1 3.1
 3.5 3.  3.5 3.2 3.8 3.8 3.7 3.2 3.1 2.8 3.3 2.9 2.  2.2 2.9 3.  2.2 3.2
 2.5 2.9 2.8 2.9 2.4 2.7 3.  3.1 3.  2.6 2.6 2.7 2.9 2.5 3.3 3.  3.  2.5
 2.5 3.2 3.  2.8 3.  2.6 3.2 2.8 3.3 2.8 2.8 2.8 2.8 2.6 3.4 3.  3.1 2.7
 3.3 2.5 3.4]
c[0,0]=1.0, a[0,0]=5.1
l. The shape of array l is (100, 6)
```


In [34]:
print(b[:10])
print(b[9:20])
print(b[50:])
print(b[-5:])
print(b[::3])
print("f=", b[4:100:5])
print("g= ", a[:10])
print("h= ", a[10:20, -2:])
print("i=", a[::2, 1])
c = a[:20, :2].copy()
print("j=", c)
c[0, 0] = 1
print(a[0, 0])
print(c[0, 0])
l = a.reshape(100, 6)
print(l.shape)

[3.5 3.  3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1]
[3.1 3.7 3.4 3.  3.  4.  4.4 3.9 3.5 3.8 3.8]
[3.2 3.2 3.1 2.3 2.8 2.8 3.3 2.4 2.9 2.7 2.  3.  2.2 2.9 2.9 3.1 3.  2.7
 2.2 2.5 3.2 2.8 2.5 2.8 2.9 3.  2.8 3.  2.9 2.6 2.4 2.4 2.7 2.7 3.  3.4
 3.1 2.3 3.  2.5 2.6 3.  2.6 2.3 2.7 3.  2.9 2.9 2.5 2.8 3.3 2.7 3.  2.9
 3.  3.  2.5 2.9 2.5 3.6 3.2 2.7 3.  2.5 2.8 3.2 3.  3.8 2.6 2.2 3.2 2.8
 2.8 2.7 3.3 3.2 2.8 3.  2.8 3.  2.8 3.8 2.8 2.8 2.6 3.  3.4 3.1 3.  3.1
 3.1 3.1 2.7 3.2 3.3 3.  2.5 3.  3.4 3. ]
[3.  2.5 3.  3.4 3. ]
[3.5 3.1 3.4 3.1 3.  4.4 3.8 3.7 3.4 3.5 3.1 4.2 3.5 3.4 3.2 3.  3.7 3.2
 2.8 2.4 2.  2.9 3.  2.5 2.5 3.  2.9 2.4 3.  2.3 2.6 2.3 2.9 2.8 3.  3.
 2.5 2.7 2.8 3.8 3.2 2.7 2.8 3.  2.8 3.  3.  3.1 3.3 3. ]
f= [3.6 3.1 4.  3.8 3.4 3.2 3.1 3.4 3.8 3.3 2.8 2.7 2.9 2.5 2.9 2.6 3.  2.5
 2.7 2.8]
g=  [[5.1 3.5 1.4 0.2 4.9 3. ]
 [1.4 0.2 4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2 5.  3.6]
 [1.4 0.2 5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3 5.  3.4]
 [1.5 0.2 4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1 5.4 3.7]
 

## 4. Concatenation
a. Create a new array ca that concatenates the second column of array a with array b
b. Create a new array cb that concatenates the first 10 and last then rows of array a



In [39]:
a.dtype
b.dtype
    # a and b gotta be the same type to concatenate

ca = np.concatenate([a[:, 1], b])
print(ca)

cb = np.concatenate([a[:10], a[-10:]])
print(cb)

[3.5 0.2 3.1 0.2 3.4 0.2 3.1 0.2 3.  0.1 4.4 0.4 3.8 0.3 3.7 0.2 3.4 0.2
 3.5 0.2 3.1 0.4 4.2 0.2 3.5 0.1 3.4 0.3 3.2 0.6 3.  0.2 3.7 0.2 3.2 1.5
 2.8 1.3 2.4 1.3 2.  1.5 2.9 1.3 3.  1.  2.5 1.8 2.5 1.2 3.  1.4 2.9 1.
 2.4 1.2 3.  1.6 2.3 1.3 2.6 1.4 2.3 1.3 2.9 1.3 2.8 2.5 3.  1.8 3.  1.7
 2.5 2.5 2.7 2.1 2.8 2.3 3.8 2.3 3.2 2.  2.7 2.1 2.8 1.8 3.  1.9 2.8 1.5
 3.  2.4 3.  2.1 3.1 1.9 3.3 2.3 3.  2.3 3.5 3.  3.2 3.1 3.6 3.9 3.4 3.4
 2.9 3.1 3.7 3.4 3.  3.  4.  4.4 3.9 3.5 3.8 3.8 3.4 3.7 3.6 3.3 3.4 3.
 3.4 3.5 3.4 3.2 3.1 3.4 4.1 4.2 3.1 3.2 3.5 3.6 3.  3.4 3.5 2.3 3.2 3.5
 3.8 3.  3.8 3.2 3.7 3.3 3.2 3.2 3.1 2.3 2.8 2.8 3.3 2.4 2.9 2.7 2.  3.
 2.2 2.9 2.9 3.1 3.  2.7 2.2 2.5 3.2 2.8 2.5 2.8 2.9 3.  2.8 3.  2.9 2.6
 2.4 2.4 2.7 2.7 3.  3.4 3.1 2.3 3.  2.5 2.6 3.  2.6 2.3 2.7 3.  2.9 2.9
 2.5 2.8 3.3 2.7 3.  2.9 3.  3.  2.5 2.9 2.5 3.6 3.2 2.7 3.  2.5 2.8 3.2
 3.  3.8 2.6 2.2 3.2 2.8 2.8 2.7 3.3 3.2 2.8 3.  2.8 3.  2.8 3.8 2.8 2.8
 2.6 3.  3.4 3.1 3.  3.1 3.1 3.1 2.7 3.2 3.3 3.  2.5 3